[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "osc"
dynamic = ["version"]
description = "Command-line client for the Open Build Service"
readme = "README.md"
requires-python = ">=3.6"
license = "GPL-2.0-or-later"
keywords = ["openSUSE", "SUSE", "RPM", "build", "buildservice", "command-line"]
authors = [
    {name = "openSUSE project", email = "opensuse-buildservice@opensuse.org"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: BSD :: FreeBSD",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Build Tools",
    "Topic :: System :: Archiving :: Packaging",
]
dependencies = [
    "cryptography",
    # rpm is not available on pip, install a matching package manually prior installing osc
    "rpm",
    "ruamel.yaml",
    "urllib3",
    "typing_extensions; python_version < \"3.8\"",
]

[project.optional-dependencies]
lint = [
    "mypy",
    "ruff",
]

[project.scripts]
git-obs = "osc.commandline_git:main"
git-osc-precommit-hook = "osc.babysitter:gitOscPrecommitHook"
osc = "osc.babysitter:main"

[project.urls]
Homepage = "https://github.com/openSUSE/osc"
Repository = "https://github.com/openSUSE/osc.git"
Issues = "https://github.com/openSUSE/osc/issues"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.setuptools]
packages = [
    "osc",
    "osc._private",
    "osc.commands",
    "osc.commands_git",
    "osc.git_scm",
    "osc.gitea_api",
    "osc.obs_api",
    "osc.obs_scm",
    "osc.output",
    "osc.util",
]

[tool.setuptools.dynamic]
version = {attr = "osc.__version__"}

[tool.setuptools.package-data]
osc = ["py.typed"]
