FROM opensuse/leap:15.6

RUN zypper ar --repo http://download.opensuse.org/repositories/OBS:/Server:/Unstable/15.6/OBS:Server:Unstable.repo
RUN zypper -n --gpg-auto-import-keys refresh
RUN zypper -n install \
    bash \
    bash-completion \
    git \
    less \
    obs-api \
    obs-server \
    obs-signd \
    obs-worker \
    osc \
    openslp \
    openssl \
    perl-XML-SAX \
    rpm-build \
    systemd \
    vim \
    && rm -rf /var/cache/zypp/*

COPY container-files/ /

RUN /bin/bash /opt/setup/setup.sh \
    && /bin/bash /opt/setup/initial-data.sh \
    && /bin/bash /opt/setup/prebuilt-rpms.sh \
    && rm -rf /var/log/apache2/* \
    && rm -rf /srv/obs/log/* \
    && rm -rf /srv/obs/service/log/* \
    && rm -rf /srv/www/obs/api/log/*

# /sbin/init doesn't exist on Leap 15.6
ENTRYPOINT ["/usr/lib/systemd/systemd"]
