FROM opensuse/leap:15.6

RUN zypper -n modifyrepo --disable repo-openh264 || : \
    && zypper ar --repo http://download.opensuse.org/repositories/OBS:/Server:/Unstable/15.6/OBS:Server:Unstable.repo \
    && zypper ar --repo http://download.opensuse.org/repositories/devel:/tools:/scm/15.6/devel:tools:scm.repo \
    && zypper ar --repo https://download.opensuse.org/repositories/devel:/Factory:/git-workflow/15.6/devel:Factory:git-workflow.repo \
    && zypper -n --gpg-auto-import-keys refresh

RUN zypper -n install \
    bash \
    bash-completion \
    crun \
    fuse-overlayfs \
    git \
    gitea-action-runner \
    less \
    obs-api \
    obs-gitea-bridge \
    obs-server \
    obs-signd \
    obs-worker \
    osc \
    openslp \
    openssl \
    perl-XML-SAX \
    podman \
    podman-docker \
    rpm-build \
    sqlite3 \
    systemd \
    vim \
    && zypper -n install --repo=devel_tools_scm gitea \
    && rm -rf /var/cache/zypp/*

COPY container-files/ /

RUN /bin/bash /opt/setup/setup.sh \
    && /bin/bash /opt/setup/initial-data.sh \
    && /bin/bash /opt/setup/prebuilt-rpms.sh \
    && /bin/bash /opt/setup/gitea.sh \
    && rm -rf /var/log/apache2/* \
    && rm -rf /srv/obs/log/* \
    && rm -rf /srv/obs/service/log/* \
    && rm -rf /srv/www/obs/api/log/*

# /sbin/init doesn't exist on Leap 15.6
ENTRYPOINT ["/usr/lib/systemd/systemd"]
