FROM registry.suse.com/bci/bci-base:15.7

RUN zypper ar --repo http://download.opensuse.org/repositories/OBS:/Server:/Unstable/15.7/OBS:Server:Unstable.repo \
    && zypper ar --repo http://download.opensuse.org/repositories/devel:/tools:/scm/15.7/devel:tools:scm.repo \
    && zypper ar --repo https://download.opensuse.org/repositories/devel:/Factory:/git-workflow/15.7/devel:Factory:git-workflow.repo \
    && zypper -n --gpg-auto-import-keys refresh

RUN zypper -n install \
    bash \
    bash-completion \
    fuse-overlayfs \
    git \
    gitea-action-runner \
    less \
    obs-api \
    obs-gitea-bridge \
    obs-server \
    obs-signd \
    obs-worker \
    osc \
    openslp \
    openssl \
    perl-XML-SAX \
    podman \
    podman-docker \
    rpm-build \
    sqlite3 \
    systemd \
    vim \
    devel_Factory_git-workflow:gitea \
    # gd package is not available in the repos, but required by obs-api-deps -> perl-GD; we'll include it from leap 15.6
    https://download.opensuse.org/distribution/leap/15.6/repo/oss/x86_64/gd-2.2.5-11.3.1.x86_64.rpm \
    && rm -rf /var/cache/zypp/*

COPY container-files/ /

RUN /bin/bash /opt/setup/setup.sh \
    && /bin/bash /opt/setup/initial-data.sh \
    && /bin/bash /opt/setup/prebuilt-rpms.sh \
    && /bin/bash /opt/setup/gitea.sh \
    && rm -rf /var/log/apache2/* \
    && rm -rf /srv/obs/log/* \
    && rm -rf /srv/obs/service/log/* \
    && rm -rf /srv/www/obs/api/log/*

# /sbin/init doesn't exist on Leap 15.6
ENTRYPOINT ["/usr/lib/systemd/systemd"]
