Feature: `git-obs staging group` command


Background:
   Given I set working directory to "{context.osc.temp}"

@destructive
Scenario: Conflicts check for --fork-repo and --target
    When I execute git-obs with args "staging group --target pool/test-GitPkgA#1 --fork-repo myfork pool/test-GitPkgA#2 pool/test-GitPkgA#3"
    Then the exit code is 2
    And stderr contains "--fork-repo conflicts with --target"

@destructive
Scenario: Group PRs then add and remove one using --target and staging remove
    # Setup:
    #   - Bob creates package PRs for pkgA, pkgB and pkgC
    #   - Admin creates staging PRs Leap#1 (pkgA), Leap#2 (pkgB), Leap#3 (pkgC)
    #   - Bob groups Leap#1 + Leap#2 → creates Leap#4 from Bob's fork
    #   - Bob adds Leap#3 to the group using --target openSUSE/Leap#4
    #   - Bob removes Leap#3 from the group using staging remove
    Given I use git-obs login "bob"
      # Package PR 1 (Bob → pkgA)
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Bob/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2 (Bob → pkgB)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Bob/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
      # Package PR 3 (Bob → pkgC)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgC"
      And I execute git-obs with args "repo clone Bob/test-GitPkgC --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgC"
      And I execute "git checkout -b pkg3"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.3@' *.spec"
      And I execute "git commit -m 'v1.3' -a"
      And I execute "git push origin pkg3"
      And I execute git-obs with args "pr create --title 'Package update 3' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Bob/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add bob ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Bob/test-GitPkgA.git"
      And I execute "git fetch bob pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Bob/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add bob ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Bob/test-GitPkgB.git"
      And I execute "git fetch bob pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Staging Project PR 3 (update submodule to Bob/test-GitPkgC pkg3)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgC"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgC"
      And I execute "git remote add bob ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Bob/test-GitPkgC.git"
      And I execute "git fetch bob pkg3"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgC"
      And I execute "git commit -m 'Update test-GitPkgC submodule'"
      And I execute "git push origin leap-pkgC"
      And I execute git-obs with args "pr create --title 'Staging Group C' --description='PR: pool/test-GitPkgC!1' --target-branch factory --self"
      # Add labels
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/3/labels --data='{{"labels": ["staging/Backlog"]}}'"
    Given I use git-obs login "bob"
      # Bob groups Leap#1 + Leap#2 → creates Leap#4 from Bob's fork
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2"
      Then the exit code is 0
      And stderr contains "WARNING: No fork organization specified. Defaulting to a private fork in 'Bob'."
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/4 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"
      And stdout contains "PR: pool/test-gitpkgb!1"
      # Bob adds Leap#3 (pkgC) to the existing group
      When I execute git-obs with args "staging group openSUSE/Leap#3 --target openSUSE/Leap#4"
      Then the exit code is 0
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/4 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"
      And stdout contains "PR: pool/test-gitpkgb!1"
      And stdout contains "PR: pool/test-gitpkgc!1"
      # Bob removes Leap#3 (pkgC) from the group
      When I execute git-obs with args "staging remove openSUSE/Leap#4 pool/test-GitPkgC#1"
      Then the exit code is 0
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/4 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"
      And stdout contains "PR: pool/test-gitpkgb!1"
      And stdout doesn't contain "PR: pool/test-gitpkgc!1"
      
@destructive
Scenario: Collaborator adds a staging PR to an existing group using --target
    # Setup:
    #   - Alice creates pkgA and pkgB package PRs
    #   - Bob creates pkgC package PR
    #   - Admin creates staging PRs Leap#1 (pkgA), Leap#2 (pkgB), Leap#3 (pkgC)
    #   - Bob groups Leap#1 + Leap#2 → creates Leap#4 from Bob's fork
    #   - Admin grants Alice write access to Bob's Leap fork
    #   - Alice adds Leap#3 to the existing group via --target Leap#4
    Given I use git-obs login "alice"
      # Package PR 1 (Alice → pkgA)
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Alice/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2 (Alice → pkgB)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Alice/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
    Given I use git-obs login "bob"
      # Package PR 3 (Bob → pkgC)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgC"
      And I execute git-obs with args "repo clone Bob/test-GitPkgC --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgC"
      And I execute "git checkout -b pkg3"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.3@' *.spec"
      And I execute "git commit -m 'v1.3' -a"
      And I execute "git push origin pkg3"
      And I execute git-obs with args "pr create --title 'Package update 3' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Alice/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgA.git"
      And I execute "git fetch alice pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Alice/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgB.git"
      And I execute "git fetch alice pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Staging Project PR 3 (update submodule to Bob/test-GitPkgC pkg3)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgC"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgC"
      And I execute "git remote add bob ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Bob/test-GitPkgC.git"
      And I execute "git fetch bob pkg3"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgC"
      And I execute "git commit -m 'Update test-GitPkgC submodule'"
      And I execute "git push origin leap-pkgC"
      And I execute git-obs with args "pr create --title 'Staging Group C' --description='PR: pool/test-GitPkgC!1' --target-branch factory --self"
      # Add labels
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/3/labels --data='{{"labels": ["staging/Backlog"]}}'"
    Given I use git-obs login "bob"
      # Bob groups Leap#1 + Leap#2, creating Leap#4 from Bob's fork (Bob/Leap)
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2"
      Then the exit code is 0
      And stderr contains "WARNING: No fork organization specified. Defaulting to a private fork in 'Bob'."
    Given I use git-obs login "admin"
      # Grant Alice write access to Bob's Leap fork so she can push to it
      And I execute git-obs with args "api -X PUT /repos/Bob/Leap/collaborators/Alice --data='{{"permission": "admin"}}'"
    Given I use git-obs login "alice"
      # Alice adds Leap#3 (pkgC) to the existing staging group (Leap#4)
      When I execute git-obs with args "staging group openSUSE/Leap#3 --target openSUSE/Leap#4"
      Then the exit code is 0
      And stdout contains "Unable to update pull request openSUSE/Leap#4"
      And I execute git-obs with args "api -X GET "/repos/openSUSE/leap/pulls/4/commits" | jq '.[].commit | select (.author.name|startswith("Alice")) | .message'"
      And stdout contains "Merge package submodules from openSUSE/Leap!3"

@destructive
Scenario: Collaborator adds a staging PR to an existing org group using --target
    # Setup:
    #   - Alice creates pkgA and pkgB package PRs
    #   - Bob creates pkgC package PR
    #   - Admin creates staging PRs Leap#1 (pkgA), Leap#2 (pkgB), Leap#3 (pkgC)
    #   - Admin creates a 'devel' org and adds both Alice and Bob as members
    #   - Bob groups Leap#1 + Leap#2 using --fork-owner devel → creates Leap#4 from devel/Leap fork
    #   - Alice adds Leap#3 to the existing group via --target openSUSE/Leap#4
    Given I use git-obs login "alice"
      # Package PR 1 (Alice → pkgA)
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Alice/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2 (Alice → pkgB)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Alice/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
    Given I use git-obs login "bob"
      # Package PR 3 (Bob → pkgC)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgC"
      And I execute git-obs with args "repo clone Bob/test-GitPkgC --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgC"
      And I execute "git checkout -b pkg3"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.3@' *.spec"
      And I execute "git commit -m 'v1.3' -a"
      And I execute "git push origin pkg3"
      And I execute git-obs with args "pr create --title 'Package update 3' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Alice/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgA.git"
      And I execute "git fetch alice pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Alice/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgB.git"
      And I execute "git fetch alice pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Staging Project PR 3 (update submodule to Bob/test-GitPkgC pkg3)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgC"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgC"
      And I execute "git remote add bob ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Bob/test-GitPkgC.git"
      And I execute "git fetch bob pkg3"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgC"
      And I execute "git commit -m 'Update test-GitPkgC submodule'"
      And I execute "git push origin leap-pkgC"
      And I execute git-obs with args "pr create --title 'Staging Group C' --description='PR: pool/test-GitPkgC!1' --target-branch factory --self"
      # Add labels
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/3/labels --data='{{"labels": ["staging/Backlog"]}}'"
      # Create the 'devel' org and add both Alice and Bob as members (team id=3 is the Owners team)
      And I execute git-obs with args "api -X POST /orgs --data='{{"username": "devel"}}'"
      And I execute git-obs with args "api -X PUT '/teams/3/members/Alice'"
      And I execute git-obs with args "api -X PUT '/teams/3/members/Bob'"
    Given I use git-obs login "bob"
      # Bob groups Leap#1 + Leap#2 into devel/Leap fork → creates Leap#4
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2 --fork-owner devel"
      Then the exit code is 0
      And stderr contains "Cannot find a matching fork of openSUSE/Leap for devel, creating one..."
    Given I use git-obs login "alice"
      # Alice adds Leap#3 (pkgC) to the existing staging group (Leap#4) via devel/Leap fork
      When I execute git-obs with args "staging group openSUSE/Leap#3 --target openSUSE/Leap#4"
      Then the exit code is 0
      And stdout contains "You have push access to the head repository devel/Leap"
      And I execute git-obs with args "api -X GET "/repos/openSUSE/leap/pulls/4/commits" | jq '.[].commit | select (.author.name|startswith("Alice")) | .message'"
      And stdout contains "Merge package submodules from openSUSE/Leap!3"

@destructive
Scenario: User is a collaborator in the project repository
    # setup: create package PRs and then two staging project PRs
    Given I use git-obs login "alice"
      # Package PR 1
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Alice/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Alice/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Alice/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgA.git"
      And I execute "git fetch alice pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Alice/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgB.git"
      And I execute "git fetch alice pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Add labels and create devel org
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X PUT '/repos/openSUSE/leap/collaborators/Alice' --data='{{"permission": "write"}}'"
    Given I use git-obs login "alice"
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2"
      Then the exit code is 0
      And stdout contains "You have push access to the target repository openSUSE/Leap, the pull request will be created from a branch in the target repository."
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/3 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"
      And stdout contains "PR: pool/test-gitpkgb!1"

@destructive
Scenario: Warning when --fork-owner is not specified with multiple PRs
    # setup: create package PRs and then two staging project PRs
    Given I use git-obs login "alice"
      # Package PR 1
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Alice/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Alice/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Alice/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgA.git"
      And I execute "git fetch alice pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Alice/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgB.git"
      And I execute "git fetch alice pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Add labels
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
    Given I use git-obs login "alice"
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2"
      Then the exit code is 0
      And stderr contains "WARNING: No fork organization specified. Defaulting to a private fork in 'Alice'."
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/3 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"
      And stdout contains "PR: pool/test-gitpkgb!1"

@destructive
Scenario: Warning when --fork-owner is not specified with multiple PRs, but --fork-repo is specified
    # setup: create package PRs and then two staging project PRs
    Given I use git-obs login "alice"
      # Package PR 1
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Alice/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Alice/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Alice/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgA.git"
      And I execute "git fetch alice pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Alice/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgB.git"
      And I execute "git fetch alice pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Add labels
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
    Given I use git-obs login "alice"
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2 --fork-repo myLeap"
      Then the exit code is 0
      And stderr contains "WARNING: No fork organization specified. Defaulting to a private fork in 'Alice'."
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/3 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"
      And stdout contains "PR: pool/test-gitpkgb!1"


@destructive
Scenario: Create a fork in the specified organization
    # setup: create package PRs and then two staging project PRs
    Given I use git-obs login "alice"
      # Package PR 1
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Alice/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Alice/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Alice/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgA.git"
      And I execute "git fetch alice pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Alice/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgB.git"
      And I execute "git fetch alice pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Add labels and create devel org
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /orgs --data='{{"username": "devel"}}'"
      And I execute git-obs with args "api -X PUT '/teams/3/members/Alice'"
    Given I use git-obs login "alice"
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2 --fork-owner devel"
      Then the exit code is 0
      And stderr contains "Cannot find a matching fork of openSUSE/Leap for devel, creating one..."
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/3 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"
      And stdout contains "PR: pool/test-gitpkgb!1"

@destructive
Scenario: Create a fork in a specified organization with a different repo name
    # setup: create package PRs and then two staging project PRs
    Given I use git-obs login "alice"
      # Package PR 1
      And I execute git-obs with args "repo fork pool/test-GitPkgA"
      And I execute git-obs with args "repo clone Alice/test-GitPkgA --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgA"
      And I execute "git checkout -b pkg1"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.1@' *.spec"
      And I execute "git commit -m 'v1.1' -a"
      And I execute "git push origin pkg1"
      And I execute git-obs with args "pr create --title 'Package update 1' --description='some text' --target-branch factory"
      # Package PR 2
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo fork pool/test-GitPkgB"
      And I execute git-obs with args "repo clone Alice/test-GitPkgB --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/test-GitPkgB"
      And I execute "git checkout factory"
      And I execute "git checkout -b pkg2"
      And I execute "sed -i 's@^\(Version: *\) .*@\1 v1.2@' *.spec"
      And I execute "git commit -m 'v1.2' -a"
      And I execute "git push origin pkg2"
      And I execute git-obs with args "pr create --title 'Package update 2' --description='some text' --target-branch factory"
    Given I use git-obs login "admin"
      # Staging Project PR 1 (update submodule to Alice/test-GitPkgA pkg1)
      And I set working directory to "{context.osc.temp}"
      And I execute git-obs with args "repo clone openSUSE/Leap --no-ssh-strict-host-key-checking"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout -b leap-pkgA"
      And I set env "GIT_SSH_COMMAND" to "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i {context.fixtures}/ssh-keys/admin"
      And I execute "git submodule update --init --recursive"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgA"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgA.git"
      And I execute "git fetch alice pkg1"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgA"
      And I execute "git commit -m 'Update test-GitPkgA submodule'"
      And I execute "git push origin leap-pkgA"
      And I execute git-obs with args "pr create --title 'Staging Group A' --description='PR: pool/test-GitPkgA!1' --target-branch factory --self"
      # Staging Project PR 2 (update submodule to Alice/test-GitPkgB pkg2)
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git checkout factory"
      And I execute "git checkout -b leap-pkgB"
      And I set working directory to "{context.osc.temp}/Leap/test-GitPkgB"
      And I execute "git remote add alice ssh://gitea@localhost:$GITEA_SERVER_SSH_PORT/Alice/test-GitPkgB.git"
      And I execute "git fetch alice pkg2"
      And I execute "git checkout FETCH_HEAD"
      And I set working directory to "{context.osc.temp}/Leap"
      And I execute "git add test-GitPkgB"
      And I execute "git commit -m 'Update test-GitPkgB submodule'"
      And I execute "git push origin leap-pkgB"
      And I execute git-obs with args "pr create --title 'Staging Group B' --description='PR: pool/test-GitPkgB!1' --target-branch factory --self"
      # Add labels and create devel org
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/Backlog", "color": "ffffff"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/labels --data='{{"name": "staging/In Progress", "color": "afafaf"}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/1/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /repos/openSUSE/Leap/issues/2/labels --data='{{"labels": ["staging/Backlog"]}}'"
      And I execute git-obs with args "api -X POST /orgs --data='{{"username": "devel"}}'"
      And I execute git-obs with args "api -X PUT '/teams/3/members/Alice'"
    Given I use git-obs login "alice"
      When I execute git-obs with args "staging group openSUSE/Leap#1 openSUSE/Leap#2 --fork-owner devel --fork-repo myLeap"
      Then the exit code is 0
      And stderr contains "Fork devel/myLeap doesn't exist, creating it..."
      And I execute git-obs with args "api -X GET /repos/openSUSE/Leap/pulls/3 | jq .body"
      And stdout contains "PR: pool/test-gitpkga!1"